name: Jolt (Develop)

on:
  push:
    branches:
      - "develop"

jobs:
  test-with-jolt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install latest Jolt
        id: setup-jolt
        uses: jlt-commons/setup-jolt@v1
        with:
          version: 'latest'
      - name: Cache All The Things
        uses: actions/cache@v6
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
            ~/.deps.clj
          key: ${{ runner.os }}-jolt-${{ steps.setup-jolt.outputs.version }}-${{ hashFiles('**/deps.edn', '**/bb.edn') }}
      - name: Run Tests on Jolt
        run: jolt --version && jolt -M:jolt:test:runner
