name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21', '25' ]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Setup Clojure and Babashka
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.5.1645'
          bb: latest
      - name: Cache All The Things
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
            ~/.deps.clj
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn', '**/bb.edn') }}
      - name: Run Tests
        run: bb ci
      - name: Check cljdoc.edn
        run: curl -fsSL https://raw.githubusercontent.com/cljdoc/cljdoc/master/script/verify-cljdoc-edn | bash -s doc/cljdoc.edn
