name: Release Version

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Clojure and Babashka
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.5.1645'
          bb: latest
      - name: Cache All The Things
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
            ~/.deps.clj
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn', '**/bb.edn') }}
      - name: Run Tests, Build JAR, and Deploy
        run: bb ci:deploy
        env:
          CLOJARS_PASSWORD: ${{secrets.DEPLOY_TOKEN}}
          CLOJARS_USERNAME: ${{secrets.DEPLOY_USERNAME}}
