name: Babashka tests

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Clojure CLI
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.1.1550'
          bb: latest
      - name: Cache All The Things
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn', '**/bb.edn') }}
      - name: Run Tests
        run: bb test:bb
